FROM node:22-alpine

WORKDIR /app

COPY package.json yarn.lock ./
COPY apps/web/package.json apps/web/package.json
COPY packages/db/package.json packages/db/package.json

RUN yarn install --frozen-lockfile

COPY . .
RUN yarn workspace web build

ENV NODE_ENV=production
EXPOSE 3000
CMD ["yarn", "workspace", "web", "start"]
